export const SETTING_CHANNEL = 'SETTINGS';

export const SETTING_KEYS = {
  SITE_NAME: 'siteName',
  LOGO_URL: 'logoUrl',
  FAVICON: 'favicon',
  LOGIN_PLACEHOLDER_IMAGE: 'loginPlaceholderImage',
  REQUIRE_EMAIL_VERIFICATION: 'requireEmailVerification',
  ADMIN_EMAIL: 'adminEmail',
  SENDER_EMAIL: 'senderEmail',
  META_KEYWORDS: 'metaKeywords',
  META_DESCRIPTION: 'metaDescription',
  HEADER_SCRIPT: 'headerScript',
  AFTER_BODY_SCRIPT: 'afterBodyScript',
  MONTHLY_SUBSCRIPTION_COMMISSION: 'monthlySubscriptionCommission',
  YEARLY_SUBSCRIPTION_COMMISSION: 'yearlySubscriptionCommission',
  VIDEO_SALE_COMMISSION: 'videoSaleCommission',
  GALLERY_SALE_COMMISSION: 'gallerySaleCommission',
  PRODUCT_SALE_COMMISSION: 'productSaleCommission',
  FEED_SALE_COMMISSION: 'feedSaleCommission',
  TIP_COMMISSION: 'tipCommission',
  STREAM_COMMISSION: 'streamCommission',
  MESSAGE_COMMISSION: 'messageCommission',
  CCBILL_CLIENT_ACCOUNT_NUMBER: 'ccbillClientAccountNumber',
  CCBILL_DATALINK_USERNAME: 'ccbillDatalinkUsername',
  CCBILL_DATALINK_PASSWORD: 'ccbillDatalinkPassword',
  CCBILL_SUB_ACCOUNT_NUMBER: 'ccbillSubAccountNumber',
  CCBILL_FLEXFORM_ID: 'ccbillFlexformId',
  CCBILL_SALT: 'ccbillSalt',
  CCBILL_CURRENCY_CODE: 'ccbilCurrencyCode',
  USE_SENDGRID_TRANSPORTER: 'useSengridTransporter',
  SMTP_TRANSPORTER: 'smtpTransporter',
  GOOGLE_ANALYTICS_CODE: 'gaCode',
  MAINTENANCE_MODE: 'maintenanceMode',
  PERFORMER_VERIFY_NUMBER: 'performerVerifyNumber',
  TWITTER_CLIENT_ID: 'twitterClientId',
  TWITTER_CLIENT_SECRET: 'twitterClientSecret',
  GOOGLE_CLIENT_ID: 'googleClientId',
  GOOGLE_CLIENT_SECRET: 'googleClientSecret',
  VIEWER_URL: 'viewerURL',
  PUBLISHER_URL: 'publisherURL',
  SUBSCRIBER_URL: 'subscriberUrl',
  OPTION_FOR_BROADCAST: 'optionForBroadcast',
  OPTION_FOR_PRIVATE: 'optionForPrivate',
  OPTION_FOR_GROUP: 'optionForGroup',
  SECURE_OPTION: 'secureOption',
  ANT_MEDIA_API_ENDPOINT: 'AntMediaApiEndpoint',
  ANT_MEDIA_APPNAME: 'AntMediaAppname',
  ANT_MEDIA_ENTERPRISE: 'AntMediaEnterprise',
  FOOTER_CONTENT: 'footerContent',
  USER_BENEFIT: 'userBenefit',
  MODEL_BENEFIT: 'modelBenefit',
  GOOGLE_RECAPTCHA_SITE_KEY: 'googleReCaptchaSiteKey',
  GOOGLE_RECAPTCHA_SECRET_KEY: 'googleReCaptchaSecretKey',
  ENABLE_GOOGLE_RECAPTCHA: 'enableGoogleReCaptcha',
  BITPAY_PRODUCTION_MODE: 'bitpayProductionMode',
  BITPAY_API_TOKEN: 'bitpayApiToken',
  TOKEN_CONVERSION_RATE: 'tokenConversionRate',
  STRIPE_PUBLISHABLE_KEY: 'stripePublishableKey',
  STRIPE_SECRET_KEY: 'stripeSecretKey',
  AGORA_APPID: 'agoraAppId',
  AGORA_ENABLE: 'agoraEnable',
  PAYMENT_GATEWAY: 'paymentGateway',
  VERIFF_ENABLED: 'veriffEnabled',
  VERIFF_PUBLIC_KEY: 'veriffPublicKey',
  VERIFF_BASE_URL: 'veriffBaseUrl'
};

export const MENU_SECTION = {
  MAIN: 'main',
  HEADER: 'header',
  FOOTER: 'footer'
};

export const RECEIVED_PAID_TOKEN_EVENT = 'RECEIVED_PAID_TOKEN_EVENT';

export const HEIGHTS = [
  { value: 'under_140', text: 'Under 140cm' },
  { value: '140_142', text: '140cm to 142cm' },
  { value: '143_145', text: '143cm to 145cm' },
  { value: '146_148', text: '146cm to 148cm' },
  { value: '149_151', text: '149cm to 151cm' },
  { value: '152_154', text: '152cm to 154cm' },
  { value: '155_157', text: '155cm to 157cm' },
  { value: '158_160', text: '158cm to 160cm' },
  { value: '161_163', text: '161cm to 163cm' },
  { value: '164_166', text: '164cm to 166cm' },
  { value: '167_169', text: '167cm to 169cm' },
  { value: '170_172', text: '170cm to 172cm' },
  { value: '173_175', text: '173cm to 175cm' },
  { value: '176_178', text: '176cm to 178cm' },
  { value: '179_181', text: '179cm to 181cm' },
  { value: '182_184', text: '182cm to 184cm' },
  { value: '185_187', text: '185cm to 187cm' },
  { value: '188_190', text: '188cm to 190cm' },
  { value: 'over_190', text: 'Over 190cm' }
];

export const WEIGHTS = [
  { value: 'under_40', text: 'Under 40kg' },
  { value: '40_42', text: '40kg to 42kg' },
  { value: '43_45', text: '43kg to 45kg' },
  { value: '46_48', text: '46kg to 48kg' },
  { value: '49_51', text: '49kg to 51kg' },
  { value: '52_54', text: '52kg to 54kg' },
  { value: '55_57', text: '55kg to 57kg' },
  { value: '58_60', text: '58kg to 60kg' },
  { value: '61_63', text: '61kg to 63kg' },
  { value: '64_66', text: '64kg to 66kg' },
  { value: '67_69', text: '67kg to 69kg' },
  { value: '70_72', text: '70kg to 72kg' },
  { value: '73_75', text: '73kg to 75kg' },
  { value: '76_78', text: '76kg to 78kg' },
  { value: '79_81', text: '79kg to 81kg' },
  { value: '82_84', text: '82kg to 84kg' },
  { value: '85_87', text: '85kg to 87kg' },
  { value: '88_90', text: '88kg to 90kg' },
  { value: '91_93', text: '91kg to 93kg' },
  { value: '94_96', text: '94kg to 96kg' },
  { value: '97_99', text: '97kg to 99kg' },
  { value: 'over_100', text: 'Over 100kg' }
];
